### ISSUE TITLE
[New Component] Breadcrumbs

### ISSUE THREAD

**Issue by heycorwin** [near/near-discovery-components#217]
Breadcrumbs indicate a page's or view's relationship to its parent and child pages.

Figma Library Component: https://www.figma.com/file/hbEv4eGUqzov3spuVgn5ig/Components?type=design&node-id=1604-1877&mode=dev

```[tasklist]
### Tasks
- [x] https://github.com/near/near-discovery-components/issues/236
- [ ] https://github.com/near/near-discovery-components/issues/238
- [ ] https://github.com/near/near-discovery-components/issues/237
```
